### ISSUE TITLE
Make mod serverside?

### ISSUE THREAD

**Issue by DeForce** [hilburn/Squidless#1]
Good Day,

I have saw your post on reddit that you created this mod for squid-spawn rate reduction and i'm in need to use it.
We have a server that have a lot of oceans and players build bases there...
And there are like 400+ squids all the time...

Seems like your mod does only change it on server with no configs, is it possible to tweak mod to not  need to be on client side?

**Comment by hilburn** [comment]
Pretty sure it is... unless i was lied to about what something does.. have you tried it?

**Comment by DeForce** [comment]
I have tried putting it to server and clients was requesting this mod to be in their clients. I didn't try in client side...

**Comment by hilburn** [comment]
Done
